
# 应用服务 WEB 访问端口
server:
  port: 8091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xyx?useSSL=false&useUnicode=true
    username: user
    password: pass

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  servlet:
    multipart:
      enabled: true # 开启文件上传
      max-request-size: 500MB
      max-file-size: 500MB




upload:
  url: 'http://localhost:9000/'
  access_key: 'minio'
  secret_key: 'minio123'
  bucket: xyx
